// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApo3Q2q8U6LPOTuV2RLCJiXEQj3zosQ7k',
    appId: '1:465767958053:web:a4f9cc2c14444023a721cc',
    messagingSenderId: '465767958053',
    projectId: 'flutter-firebase-login-ecfc1',
    authDomain: 'flutter-firebase-login-ecfc1.firebaseapp.com',
    storageBucket: 'flutter-firebase-login-ecfc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPXVli5EN10B823VONV0bk-H9v5tUP-g8',
    appId: '1:465767958053:android:8ea933b83ac176eea721cc',
    messagingSenderId: '465767958053',
    projectId: 'flutter-firebase-login-ecfc1',
    storageBucket: 'flutter-firebase-login-ecfc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBX04oOQY6jfi4pO9y7rm6ao7sMXPJuQ',
    appId: '1:465767958053:ios:3e397dc6cffb819aa721cc',
    messagingSenderId: '465767958053',
    projectId: 'flutter-firebase-login-ecfc1',
    storageBucket: 'flutter-firebase-login-ecfc1.appspot.com',
    iosBundleId: 'com.flutter.firelogin.yh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApo3Q2q8U6LPOTuV2RLCJiXEQj3zosQ7k',
    appId: '1:465767958053:web:659a78b728793378a721cc',
    messagingSenderId: '465767958053',
    projectId: 'flutter-firebase-login-ecfc1',
    authDomain: 'flutter-firebase-login-ecfc1.firebaseapp.com',
    storageBucket: 'flutter-firebase-login-ecfc1.appspot.com',
  );
}
